name: Update Codewars Stats

on:
  schedule:
    - cron: "0 2 * * *"   # Her gün sabah 05:00 Türkiye saati
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run script
        run: node .github/scripts/codewars.js

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "update: Codewars stats"
          git push
